[package]
name = "day6_prime_fork"
version = "0.1.0"
edition = "2021"


[profile.test]
# we make extensive use of SIMD intrinsics, which are extremely slow at -O0
opt-level = 1

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
